version: '2'
services:
  fastapi-sqlalchemy:
    build: .
    container_name: "fastapi" 
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000" 
    depends_on:
      - db
    restart: always
  db:
    container_name: postgres-db
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=perseus_db
    restart: always

volumes:
  postgres_data: 